# -*- coding: utf-8 -*-
"""apex_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pCjXsVOIakEgMH369suZU84Wcj8SBGTG
"""

pip install fastf1 matplotlib numpy pandas

import os
import fastf1
import numpy as np
import pandas as pd
from scipy.signal import argrelextrema
from scipy.interpolate import splprep, splev
import plotly.graph_objects as go


team_colors = {
    "VER": "#3671C6", "PER": "#1E41FF",
    "LEC": "#DC0000", "SAI": "#DC0000",
    "HAM": "#6CD3BF", "RUS": "#6CD3BF",
    "NOR": "#FF8700", "PIA": "#FF8700",
    "ALO": "#358C75", "STR": "#358C75",
    "GAS": "#2293D1", "OCO": "#2293D1",
    "BOT": "#00E0CA", "ZHO": "#00E0CA",
    "ALB": "#005AFF", "SAR": "#005AFF",
    "MAG": "#B6BABD", "HUL": "#B6BABD",
    "TSU": "#2B4562", "RIC": "#2B4562"
}

if not os.path.exists("f1cache"):
    os.makedirs("f1cache")
fastf1.Cache.enable_cache("f1cache")


session = fastf1.get_session(2023, "Monza", "R")
session.load()


def curvature(x, y):
    dx = np.gradient(x)
    dy = np.gradient(y)
    ddx = np.gradient(dx)
    ddy = np.gradient(dy)
    return np.abs(dx * ddy - dy * ddx) / (dx*dx + dy*dy)**1.5


apex_data = {}

for drv in session.drivers:
    abbr = session.get_driver(drv)["Abbreviation"]
    lap = session.laps.pick_drivers(drv).pick_fastest()
    if lap is None:
        continue

    tel = lap.get_car_data().add_distance()
    pos = lap.get_pos_data()

    speed = tel["Speed"].values
    dist = tel["Distance"].values

    # curvature from GPS
    kappa = curvature(pos["X"], pos["Y"])

    # speed minima = apex candidate
    speed_mins = argrelextrema(speed, np.less)[0]

    # curvature maxima = strong corner
    curve_peaks = argrelextrema(kappa, np.greater)[0]

    apex_idx = []
    for s in speed_mins:
        nearest = np.abs(curve_peaks - s).argmin()
        if np.abs(curve_peaks[nearest] - s) < 25:
            apex_idx.append(s)

    apex_idx = sorted(list(set(apex_idx)))[:12]
    apex_data[abbr] = [(dist[i], speed[i]) for i in apex_idx]


all_d = []
for drv in apex_data:
    for d, s in apex_data[drv]:
        all_d.append(d)

all_d = np.array(sorted(all_d))
bins = np.linspace(all_d.min(), all_d.max(), 12)

apex_centers = []
for i in range(len(bins)-1):
    mask = (all_d >= bins[i]) & (all_d < bins[i+1])
    if np.any(mask):
        apex_centers.append(all_d[mask].mean())


battle = []
for i, center in enumerate(apex_centers):
    row = {"corner": f"T{i+1}"}
    for drv in apex_data:
        distances = np.array([d for d, _ in apex_data[drv]])
        speeds = np.array([s for _, s in apex_data[drv]])
        idx = np.abs(distances - center).argmin()
        row[drv] = speeds[idx]
    battle.append(row)

df = pd.DataFrame(battle)

# winner per corner
winners = []
for i, row in df.iterrows():
    r = row.drop("corner")
    fastest = r.idxmax()
    winners.append((row["corner"], fastest, r[fastest]))


verlap = session.laps.pick_drivers("VER").pick_fastest()
tel_ver = verlap.get_car_data().add_distance()
pos_ver = verlap.get_pos_data()

# CLOSED CURVE SPLINE → NO GAP
tck, _ = splprep([pos_ver.X, pos_ver.Y], s=2.0, per=True)
sx, sy = splev(np.linspace(0, 1, 3000), tck)

# stylized neon geometry
sx = sx * 1.2 + 0.15*np.sin(sy/14)
sy = sy * 1.25 + 0.15*np.cos(sx/18)

# apex positions on stylized track
track_apex_x = []
track_apex_y = []
for c in apex_centers:
    idx = int((c / tel_ver.Distance.max()) * (len(sx)-1))
    track_apex_x.append(sx[idx])
    track_apex_y.append(sy[idx])


fig = go.Figure()

# Glow
fig.add_trace(go.Scatter(
    x=sx, y=sy,
    mode="lines",
    line=dict(width=22, color="rgba(0,255,255,0.18)"),
    hoverinfo="skip"
))

# Neon track
fig.add_trace(go.Scatter(
    x=sx, y=sy,
    mode="lines",
    line=dict(width=4, color="#00F5FF"),
    hoverinfo="skip"
))

flag_x = sx[0]
flag_y = sy[0]

fig.add_trace(go.Scatter(
    x=[flag_x],
    y=[flag_y],
    mode="text",
    text=["🏁"],
    textfont=dict(size=40),
    hovertemplate="<b>Start/Finish Line</b><extra></extra>"
))


fig.add_trace(go.Scatter(
    x=track_apex_x,
    y=track_apex_y,
    mode="markers+text",
    marker=dict(
        size=26,
        color=[team_colors.get(w[1], "white") for w in winners],
        line=dict(color="white", width=2)
    ),
    text=[f"{w[0]} • {w[1]} • {w[2]:.1f} km/h" for w in winners],
    textposition="top center",
    textfont=dict(color="white", size=12),
    hovertemplate="<b>%{text}</b><extra></extra>"
))

fig.update_layout(
    width=1500,
    height=820,
    plot_bgcolor="#050505",
    paper_bgcolor="#050505",
    xaxis=dict(visible=False),
    yaxis=dict(visible=False),
    title=dict(
        text="REAL APEX DETECTION • FASTEST DRIVER PER CORNER • TEAM COLORS • 🏁 START LINE",
        x=0.38,
        font=dict(size=28, color="cyan")
    )
)

fig.show()